codecov:
  branch: main

comment: 
  layout: ""
  require_base: false
  require_head: yes 
  branches:
  - "M3GmRUVDUZcwg8nK1GmvERHAttwdAYVH" # set it to M3GmRUVDUZcwg8nK1GmvERHAttwdAYVH so that no comments are written.

ignore:
  - "examples/*.go"