name: unit-tests

on:
  push:
    branches:
      - "**"
      - "!production"

jobs:
  unit-tests:
    name: test the go code
    runs-on: ubuntu-latest

    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
      - name: run go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          go test -race -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out